In [ ]:
import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":memory:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

In [ ]:
cur.executescript('''
DROP TABLE IF EXISTS alumnos;

CREATE TABLE alumnos (
    id_alumno integer PRIMARY KEY,
    nombre varchar(50) NOT NULL,
    grado varchar(10) NOT NULL,
    edad integer NOT NULL,
    promedio decimal(4,2)
);

''')
conn.commit()
print("Tablas creadas: alumnos")

Tablas creadas: alumnos

In [ ]:
# INSERT: alta de alumnos
run("""INSERT INTO alumnos (nombre, grado, edad, promedio) VALUES
    ('Juan','5to A', 15, 7.8),
    ('Pedro', '3ro B', 13, 6.9),
    ('Maria', '2do A', 14, 9.0);""")

query("SELECT * FROM alumnos")

OK -> INSERT INTO alumnos (nombre, grado, edad, promedio) VALUES ...

   id_alumno nombre  grado  edad  promedio
0          1   Juan  5to A    15       7.8
1          2  Pedro  3ro B    13       6.9
2          3  Maria  2do A    14       9.0

In [ ]:
# UPDATE: modificación de registros (aumento del promedio de alumnos 3ro B)
run("UPDATE alumnos SET promedio = promedio * 1.10 WHERE grado = '3ro B';")
query("SELECT id_alumno, nombre, grado, edad, promedio FROM alumnos WHERE grado = 'fuerte'")

OK -> UPDATE alumnos SET promedio = promedio * 1.10 WHERE grado = '3ro B'; ...

Empty DataFrame
Columns: [id_alumno, nombre, grado, edad, promedio]
Index: []

In [ ]:
# DELETE: eliminación de registros (se retira un alumno)
run("DELETE FROM alumnos WHERE nombre = 'Juan';")
query("SELECT * FROM alumnos")

OK -> DELETE FROM alumnos WHERE nombre = 'Juan'; ...

   id_alumno nombre  grado  edad  promedio
0          2  Pedro  3ro B    13      7.59
1          3  Maria  2do A    14      9.00